version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: agenda-petshop
    ports:
      - 3306:3306
    networks:
      - app-bridge

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - app-bridge

  app:
    image: node:lts-alpine
    restart: always
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app/
    entrypoint: ["node", "./server.js"]
    networks:
      - app-bridge

networks:
  app-bridge:
    driver: bridge
